export default {
  primaryLight: "#70dde9",
  primary: "#35abb7",
  primaryDark: "#007b87",
  secondaryLight: "#a19485",
  secondary: "#726658",
  secondaryDark: "#463c2f",
  background: "#F0F0F7",
  cardBackgound: "#FFF",
  resetColor: "#3F3F41",
  titleInPrimary: "#FFFFFF",
  textInPrimary: "#E6E6F0",
  textTitle: "#42edff",
  textComplement: "#75727e",
  textBase: "#6A6180",
  lineInWhite: "#afafb8",
  inputBackground: "#F8F8FC",
  buttonText: "#FFFFFF",
  boxBase: "#FFFFFF",
  boxFooter: "#FAFAFC",
  smallInfo: "#C1BCCC",
};
